/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var SolidityTypes_pb = require('./SolidityTypes_pb.js');
goog.object.extend(proto, SolidityTypes_pb);
var IssuanceData_pb = require('./IssuanceData_pb.js');
goog.object.extend(proto, IssuanceData_pb);
goog.exportSymbol('proto.BorrowingCompleteProperties', null, global);
goog.exportSymbol('proto.BorrowingMakerParameters', null, global);
goog.exportSymbol('proto.BorrowingProperties', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.BorrowingMakerParameters = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.BorrowingMakerParameters, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.BorrowingMakerParameters.displayName = 'proto.BorrowingMakerParameters';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.BorrowingProperties = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.BorrowingProperties, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.BorrowingProperties.displayName = 'proto.BorrowingProperties';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.BorrowingCompleteProperties = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.BorrowingCompleteProperties, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.BorrowingCompleteProperties.displayName = 'proto.BorrowingCompleteProperties';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.BorrowingMakerParameters.prototype.toObject = function(opt_includeInstance) {
  return proto.BorrowingMakerParameters.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.BorrowingMakerParameters} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.BorrowingMakerParameters.toObject = function(includeInstance, msg) {
  var f, obj = {
    collateraltokenaddress: (f = msg.getCollateraltokenaddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    borrowingtokenaddress: (f = msg.getBorrowingtokenaddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    borrowingamount: (f = msg.getBorrowingamount()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    collateralratio: (f = msg.getCollateralratio()) && SolidityTypes_pb.uint32.toObject(includeInstance, f),
    tenordays: (f = msg.getTenordays()) && SolidityTypes_pb.uint32.toObject(includeInstance, f),
    interestrate: (f = msg.getInterestrate()) && SolidityTypes_pb.uint32.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.BorrowingMakerParameters}
 */
proto.BorrowingMakerParameters.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.BorrowingMakerParameters;
  return proto.BorrowingMakerParameters.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.BorrowingMakerParameters} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.BorrowingMakerParameters}
 */
proto.BorrowingMakerParameters.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setCollateraltokenaddress(value);
      break;
    case 2:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setBorrowingtokenaddress(value);
      break;
    case 3:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setBorrowingamount(value);
      break;
    case 4:
      var value = new SolidityTypes_pb.uint32;
      reader.readMessage(value,SolidityTypes_pb.uint32.deserializeBinaryFromReader);
      msg.setCollateralratio(value);
      break;
    case 5:
      var value = new SolidityTypes_pb.uint32;
      reader.readMessage(value,SolidityTypes_pb.uint32.deserializeBinaryFromReader);
      msg.setTenordays(value);
      break;
    case 6:
      var value = new SolidityTypes_pb.uint32;
      reader.readMessage(value,SolidityTypes_pb.uint32.deserializeBinaryFromReader);
      msg.setInterestrate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.BorrowingMakerParameters.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.BorrowingMakerParameters.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.BorrowingMakerParameters} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.BorrowingMakerParameters.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCollateraltokenaddress();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getBorrowingtokenaddress();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getBorrowingamount();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getCollateralratio();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      SolidityTypes_pb.uint32.serializeBinaryToWriter
    );
  }
  f = message.getTenordays();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      SolidityTypes_pb.uint32.serializeBinaryToWriter
    );
  }
  f = message.getInterestrate();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      SolidityTypes_pb.uint32.serializeBinaryToWriter
    );
  }
};


/**
 * optional solidity.address collateralTokenAddress = 1;
 * @return {?proto.solidity.address}
 */
proto.BorrowingMakerParameters.prototype.getCollateraltokenaddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 1));
};


/** @param {?proto.solidity.address|undefined} value */
proto.BorrowingMakerParameters.prototype.setCollateraltokenaddress = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingMakerParameters.prototype.clearCollateraltokenaddress = function() {
  this.setCollateraltokenaddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingMakerParameters.prototype.hasCollateraltokenaddress = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional solidity.address borrowingTokenAddress = 2;
 * @return {?proto.solidity.address}
 */
proto.BorrowingMakerParameters.prototype.getBorrowingtokenaddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 2));
};


/** @param {?proto.solidity.address|undefined} value */
proto.BorrowingMakerParameters.prototype.setBorrowingtokenaddress = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingMakerParameters.prototype.clearBorrowingtokenaddress = function() {
  this.setBorrowingtokenaddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingMakerParameters.prototype.hasBorrowingtokenaddress = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional solidity.uint256 borrowingAmount = 3;
 * @return {?proto.solidity.uint256}
 */
proto.BorrowingMakerParameters.prototype.getBorrowingamount = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 3));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.BorrowingMakerParameters.prototype.setBorrowingamount = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingMakerParameters.prototype.clearBorrowingamount = function() {
  this.setBorrowingamount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingMakerParameters.prototype.hasBorrowingamount = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional solidity.uint32 collateralRatio = 4;
 * @return {?proto.solidity.uint32}
 */
proto.BorrowingMakerParameters.prototype.getCollateralratio = function() {
  return /** @type{?proto.solidity.uint32} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint32, 4));
};


/** @param {?proto.solidity.uint32|undefined} value */
proto.BorrowingMakerParameters.prototype.setCollateralratio = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingMakerParameters.prototype.clearCollateralratio = function() {
  this.setCollateralratio(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingMakerParameters.prototype.hasCollateralratio = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional solidity.uint32 tenorDays = 5;
 * @return {?proto.solidity.uint32}
 */
proto.BorrowingMakerParameters.prototype.getTenordays = function() {
  return /** @type{?proto.solidity.uint32} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint32, 5));
};


/** @param {?proto.solidity.uint32|undefined} value */
proto.BorrowingMakerParameters.prototype.setTenordays = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingMakerParameters.prototype.clearTenordays = function() {
  this.setTenordays(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingMakerParameters.prototype.hasTenordays = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional solidity.uint32 interestRate = 6;
 * @return {?proto.solidity.uint32}
 */
proto.BorrowingMakerParameters.prototype.getInterestrate = function() {
  return /** @type{?proto.solidity.uint32} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint32, 6));
};


/** @param {?proto.solidity.uint32|undefined} value */
proto.BorrowingMakerParameters.prototype.setInterestrate = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingMakerParameters.prototype.clearInterestrate = function() {
  this.setInterestrate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingMakerParameters.prototype.hasInterestrate = function() {
  return jspb.Message.getField(this, 6) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.BorrowingProperties.prototype.toObject = function(opt_includeInstance) {
  return proto.BorrowingProperties.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.BorrowingProperties} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.BorrowingProperties.toObject = function(includeInstance, msg) {
  var f, obj = {
    borrowingtokenaddress: (f = msg.getBorrowingtokenaddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    collateraltokenaddress: (f = msg.getCollateraltokenaddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    borrowingamount: (f = msg.getBorrowingamount()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    collateralratio: (f = msg.getCollateralratio()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    collateralamount: (f = msg.getCollateralamount()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    interestrate: (f = msg.getInterestrate()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    interestamount: (f = msg.getInterestamount()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    tenordays: (f = msg.getTenordays()) && SolidityTypes_pb.uint256.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.BorrowingProperties}
 */
proto.BorrowingProperties.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.BorrowingProperties;
  return proto.BorrowingProperties.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.BorrowingProperties} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.BorrowingProperties}
 */
proto.BorrowingProperties.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setBorrowingtokenaddress(value);
      break;
    case 2:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setCollateraltokenaddress(value);
      break;
    case 3:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setBorrowingamount(value);
      break;
    case 4:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setCollateralratio(value);
      break;
    case 5:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setCollateralamount(value);
      break;
    case 6:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setInterestrate(value);
      break;
    case 7:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setInterestamount(value);
      break;
    case 8:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setTenordays(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.BorrowingProperties.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.BorrowingProperties.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.BorrowingProperties} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.BorrowingProperties.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBorrowingtokenaddress();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getCollateraltokenaddress();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getBorrowingamount();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getCollateralratio();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getCollateralamount();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getInterestrate();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getInterestamount();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getTenordays();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
};


/**
 * optional solidity.address borrowingTokenAddress = 1;
 * @return {?proto.solidity.address}
 */
proto.BorrowingProperties.prototype.getBorrowingtokenaddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 1));
};


/** @param {?proto.solidity.address|undefined} value */
proto.BorrowingProperties.prototype.setBorrowingtokenaddress = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingProperties.prototype.clearBorrowingtokenaddress = function() {
  this.setBorrowingtokenaddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingProperties.prototype.hasBorrowingtokenaddress = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional solidity.address collateralTokenAddress = 2;
 * @return {?proto.solidity.address}
 */
proto.BorrowingProperties.prototype.getCollateraltokenaddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 2));
};


/** @param {?proto.solidity.address|undefined} value */
proto.BorrowingProperties.prototype.setCollateraltokenaddress = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingProperties.prototype.clearCollateraltokenaddress = function() {
  this.setCollateraltokenaddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingProperties.prototype.hasCollateraltokenaddress = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional solidity.uint256 borrowingAmount = 3;
 * @return {?proto.solidity.uint256}
 */
proto.BorrowingProperties.prototype.getBorrowingamount = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 3));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.BorrowingProperties.prototype.setBorrowingamount = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingProperties.prototype.clearBorrowingamount = function() {
  this.setBorrowingamount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingProperties.prototype.hasBorrowingamount = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional solidity.uint256 collateralRatio = 4;
 * @return {?proto.solidity.uint256}
 */
proto.BorrowingProperties.prototype.getCollateralratio = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 4));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.BorrowingProperties.prototype.setCollateralratio = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingProperties.prototype.clearCollateralratio = function() {
  this.setCollateralratio(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingProperties.prototype.hasCollateralratio = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional solidity.uint256 collateralAmount = 5;
 * @return {?proto.solidity.uint256}
 */
proto.BorrowingProperties.prototype.getCollateralamount = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 5));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.BorrowingProperties.prototype.setCollateralamount = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingProperties.prototype.clearCollateralamount = function() {
  this.setCollateralamount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingProperties.prototype.hasCollateralamount = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional solidity.uint256 interestRate = 6;
 * @return {?proto.solidity.uint256}
 */
proto.BorrowingProperties.prototype.getInterestrate = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 6));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.BorrowingProperties.prototype.setInterestrate = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingProperties.prototype.clearInterestrate = function() {
  this.setInterestrate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingProperties.prototype.hasInterestrate = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional solidity.uint256 interestAmount = 7;
 * @return {?proto.solidity.uint256}
 */
proto.BorrowingProperties.prototype.getInterestamount = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 7));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.BorrowingProperties.prototype.setInterestamount = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingProperties.prototype.clearInterestamount = function() {
  this.setInterestamount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingProperties.prototype.hasInterestamount = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional solidity.uint256 tenorDays = 8;
 * @return {?proto.solidity.uint256}
 */
proto.BorrowingProperties.prototype.getTenordays = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 8));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.BorrowingProperties.prototype.setTenordays = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingProperties.prototype.clearTenordays = function() {
  this.setTenordays(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingProperties.prototype.hasTenordays = function() {
  return jspb.Message.getField(this, 8) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.BorrowingCompleteProperties.prototype.toObject = function(opt_includeInstance) {
  return proto.BorrowingCompleteProperties.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.BorrowingCompleteProperties} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.BorrowingCompleteProperties.toObject = function(includeInstance, msg) {
  var f, obj = {
    issuanceproperties: (f = msg.getIssuanceproperties()) && IssuanceData_pb.IssuanceProperties.toObject(includeInstance, f),
    borrowingproperties: (f = msg.getBorrowingproperties()) && proto.BorrowingProperties.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.BorrowingCompleteProperties}
 */
proto.BorrowingCompleteProperties.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.BorrowingCompleteProperties;
  return proto.BorrowingCompleteProperties.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.BorrowingCompleteProperties} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.BorrowingCompleteProperties}
 */
proto.BorrowingCompleteProperties.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new IssuanceData_pb.IssuanceProperties;
      reader.readMessage(value,IssuanceData_pb.IssuanceProperties.deserializeBinaryFromReader);
      msg.setIssuanceproperties(value);
      break;
    case 2:
      var value = new proto.BorrowingProperties;
      reader.readMessage(value,proto.BorrowingProperties.deserializeBinaryFromReader);
      msg.setBorrowingproperties(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.BorrowingCompleteProperties.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.BorrowingCompleteProperties.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.BorrowingCompleteProperties} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.BorrowingCompleteProperties.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIssuanceproperties();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      IssuanceData_pb.IssuanceProperties.serializeBinaryToWriter
    );
  }
  f = message.getBorrowingproperties();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.BorrowingProperties.serializeBinaryToWriter
    );
  }
};


/**
 * optional IssuanceProperties issuanceProperties = 1;
 * @return {?proto.IssuanceProperties}
 */
proto.BorrowingCompleteProperties.prototype.getIssuanceproperties = function() {
  return /** @type{?proto.IssuanceProperties} */ (
    jspb.Message.getWrapperField(this, IssuanceData_pb.IssuanceProperties, 1));
};


/** @param {?proto.IssuanceProperties|undefined} value */
proto.BorrowingCompleteProperties.prototype.setIssuanceproperties = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingCompleteProperties.prototype.clearIssuanceproperties = function() {
  this.setIssuanceproperties(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingCompleteProperties.prototype.hasIssuanceproperties = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional BorrowingProperties borrowingProperties = 2;
 * @return {?proto.BorrowingProperties}
 */
proto.BorrowingCompleteProperties.prototype.getBorrowingproperties = function() {
  return /** @type{?proto.BorrowingProperties} */ (
    jspb.Message.getWrapperField(this, proto.BorrowingProperties, 2));
};


/** @param {?proto.BorrowingProperties|undefined} value */
proto.BorrowingCompleteProperties.prototype.setBorrowingproperties = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.BorrowingCompleteProperties.prototype.clearBorrowingproperties = function() {
  this.setBorrowingproperties(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.BorrowingCompleteProperties.prototype.hasBorrowingproperties = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto);
