/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var SolidityTypes_pb = require('./SolidityTypes_pb.js');
goog.object.extend(proto, SolidityTypes_pb);
var IssuanceData_pb = require('./IssuanceData_pb.js');
goog.object.extend(proto, IssuanceData_pb);
goog.exportSymbol('proto.LendingCompleteProperties', null, global);
goog.exportSymbol('proto.LendingMakerParameters', null, global);
goog.exportSymbol('proto.LendingProperties', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LendingMakerParameters = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.LendingMakerParameters, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.LendingMakerParameters.displayName = 'proto.LendingMakerParameters';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LendingProperties = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.LendingProperties, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.LendingProperties.displayName = 'proto.LendingProperties';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LendingCompleteProperties = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.LendingCompleteProperties, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.LendingCompleteProperties.displayName = 'proto.LendingCompleteProperties';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.LendingMakerParameters.prototype.toObject = function(opt_includeInstance) {
  return proto.LendingMakerParameters.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.LendingMakerParameters} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LendingMakerParameters.toObject = function(includeInstance, msg) {
  var f, obj = {
    collateraltokenaddress: (f = msg.getCollateraltokenaddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    lendingtokenaddress: (f = msg.getLendingtokenaddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    lendingamount: (f = msg.getLendingamount()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    collateralratio: (f = msg.getCollateralratio()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    tenordays: (f = msg.getTenordays()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    interestrate: (f = msg.getInterestrate()) && SolidityTypes_pb.uint256.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LendingMakerParameters}
 */
proto.LendingMakerParameters.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.LendingMakerParameters;
  return proto.LendingMakerParameters.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LendingMakerParameters} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LendingMakerParameters}
 */
proto.LendingMakerParameters.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setCollateraltokenaddress(value);
      break;
    case 2:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setLendingtokenaddress(value);
      break;
    case 3:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setLendingamount(value);
      break;
    case 4:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setCollateralratio(value);
      break;
    case 5:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setTenordays(value);
      break;
    case 6:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setInterestrate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LendingMakerParameters.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.LendingMakerParameters.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LendingMakerParameters} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LendingMakerParameters.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCollateraltokenaddress();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getLendingtokenaddress();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getLendingamount();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getCollateralratio();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getTenordays();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getInterestrate();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
};


/**
 * optional solidity.address collateralTokenAddress = 1;
 * @return {?proto.solidity.address}
 */
proto.LendingMakerParameters.prototype.getCollateraltokenaddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 1));
};


/** @param {?proto.solidity.address|undefined} value */
proto.LendingMakerParameters.prototype.setCollateraltokenaddress = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.LendingMakerParameters.prototype.clearCollateraltokenaddress = function() {
  this.setCollateraltokenaddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LendingMakerParameters.prototype.hasCollateraltokenaddress = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional solidity.address lendingTokenAddress = 2;
 * @return {?proto.solidity.address}
 */
proto.LendingMakerParameters.prototype.getLendingtokenaddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 2));
};


/** @param {?proto.solidity.address|undefined} value */
proto.LendingMakerParameters.prototype.setLendingtokenaddress = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.LendingMakerParameters.prototype.clearLendingtokenaddress = function() {
  this.setLendingtokenaddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LendingMakerParameters.prototype.hasLendingtokenaddress = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional solidity.uint256 lendingAmount = 3;
 * @return {?proto.solidity.uint256}
 */
proto.LendingMakerParameters.prototype.getLendingamount = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 3));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.LendingMakerParameters.prototype.setLendingamount = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.LendingMakerParameters.prototype.clearLendingamount = function() {
  this.setLendingamount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LendingMakerParameters.prototype.hasLendingamount = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional solidity.uint256 collateralRatio = 4;
 * @return {?proto.solidity.uint256}
 */
proto.LendingMakerParameters.prototype.getCollateralratio = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 4));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.LendingMakerParameters.prototype.setCollateralratio = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.LendingMakerParameters.prototype.clearCollateralratio = function() {
  this.setCollateralratio(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LendingMakerParameters.prototype.hasCollateralratio = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional solidity.uint256 tenorDays = 5;
 * @return {?proto.solidity.uint256}
 */
proto.LendingMakerParameters.prototype.getTenordays = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 5));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.LendingMakerParameters.prototype.setTenordays = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.LendingMakerParameters.prototype.clearTenordays = function() {
  this.setTenordays(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LendingMakerParameters.prototype.hasTenordays = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional solidity.uint256 interestRate = 6;
 * @return {?proto.solidity.uint256}
 */
proto.LendingMakerParameters.prototype.getInterestrate = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 6));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.LendingMakerParameters.prototype.setInterestrate = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.LendingMakerParameters.prototype.clearInterestrate = function() {
  this.setInterestrate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LendingMakerParameters.prototype.hasInterestrate = function() {
  return jspb.Message.getField(this, 6) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.LendingProperties.prototype.toObject = function(opt_includeInstance) {
  return proto.LendingProperties.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.LendingProperties} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LendingProperties.toObject = function(includeInstance, msg) {
  var f, obj = {
    lendingtokenaddress: (f = msg.getLendingtokenaddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    collateraltokenaddress: (f = msg.getCollateraltokenaddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    lendingamount: (f = msg.getLendingamount()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    collateralratio: (f = msg.getCollateralratio()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    collateralamount: (f = msg.getCollateralamount()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    interestrate: (f = msg.getInterestrate()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    interestamount: (f = msg.getInterestamount()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    tenordays: (f = msg.getTenordays()) && SolidityTypes_pb.uint256.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LendingProperties}
 */
proto.LendingProperties.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.LendingProperties;
  return proto.LendingProperties.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LendingProperties} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LendingProperties}
 */
proto.LendingProperties.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setLendingtokenaddress(value);
      break;
    case 2:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setCollateraltokenaddress(value);
      break;
    case 3:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setLendingamount(value);
      break;
    case 4:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setCollateralratio(value);
      break;
    case 5:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setCollateralamount(value);
      break;
    case 6:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setInterestrate(value);
      break;
    case 7:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setInterestamount(value);
      break;
    case 8:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setTenordays(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LendingProperties.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.LendingProperties.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LendingProperties} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LendingProperties.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLendingtokenaddress();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getCollateraltokenaddress();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getLendingamount();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getCollateralratio();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getCollateralamount();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getInterestrate();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getInterestamount();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getTenordays();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
};


/**
 * optional solidity.address lendingTokenAddress = 1;
 * @return {?proto.solidity.address}
 */
proto.LendingProperties.prototype.getLendingtokenaddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 1));
};


/** @param {?proto.solidity.address|undefined} value */
proto.LendingProperties.prototype.setLendingtokenaddress = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.LendingProperties.prototype.clearLendingtokenaddress = function() {
  this.setLendingtokenaddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LendingProperties.prototype.hasLendingtokenaddress = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional solidity.address collateralTokenAddress = 2;
 * @return {?proto.solidity.address}
 */
proto.LendingProperties.prototype.getCollateraltokenaddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 2));
};


/** @param {?proto.solidity.address|undefined} value */
proto.LendingProperties.prototype.setCollateraltokenaddress = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.LendingProperties.prototype.clearCollateraltokenaddress = function() {
  this.setCollateraltokenaddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LendingProperties.prototype.hasCollateraltokenaddress = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional solidity.uint256 lendingAmount = 3;
 * @return {?proto.solidity.uint256}
 */
proto.LendingProperties.prototype.getLendingamount = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 3));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.LendingProperties.prototype.setLendingamount = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.LendingProperties.prototype.clearLendingamount = function() {
  this.setLendingamount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LendingProperties.prototype.hasLendingamount = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional solidity.uint256 collateralRatio = 4;
 * @return {?proto.solidity.uint256}
 */
proto.LendingProperties.prototype.getCollateralratio = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 4));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.LendingProperties.prototype.setCollateralratio = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.LendingProperties.prototype.clearCollateralratio = function() {
  this.setCollateralratio(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LendingProperties.prototype.hasCollateralratio = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional solidity.uint256 collateralAmount = 5;
 * @return {?proto.solidity.uint256}
 */
proto.LendingProperties.prototype.getCollateralamount = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 5));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.LendingProperties.prototype.setCollateralamount = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.LendingProperties.prototype.clearCollateralamount = function() {
  this.setCollateralamount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LendingProperties.prototype.hasCollateralamount = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional solidity.uint256 interestRate = 6;
 * @return {?proto.solidity.uint256}
 */
proto.LendingProperties.prototype.getInterestrate = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 6));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.LendingProperties.prototype.setInterestrate = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.LendingProperties.prototype.clearInterestrate = function() {
  this.setInterestrate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LendingProperties.prototype.hasInterestrate = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional solidity.uint256 interestAmount = 7;
 * @return {?proto.solidity.uint256}
 */
proto.LendingProperties.prototype.getInterestamount = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 7));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.LendingProperties.prototype.setInterestamount = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.LendingProperties.prototype.clearInterestamount = function() {
  this.setInterestamount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LendingProperties.prototype.hasInterestamount = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional solidity.uint256 tenorDays = 8;
 * @return {?proto.solidity.uint256}
 */
proto.LendingProperties.prototype.getTenordays = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 8));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.LendingProperties.prototype.setTenordays = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.LendingProperties.prototype.clearTenordays = function() {
  this.setTenordays(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LendingProperties.prototype.hasTenordays = function() {
  return jspb.Message.getField(this, 8) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.LendingCompleteProperties.prototype.toObject = function(opt_includeInstance) {
  return proto.LendingCompleteProperties.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.LendingCompleteProperties} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LendingCompleteProperties.toObject = function(includeInstance, msg) {
  var f, obj = {
    issuanceproperties: (f = msg.getIssuanceproperties()) && IssuanceData_pb.IssuanceProperties.toObject(includeInstance, f),
    lendingproperties: (f = msg.getLendingproperties()) && proto.LendingProperties.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LendingCompleteProperties}
 */
proto.LendingCompleteProperties.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.LendingCompleteProperties;
  return proto.LendingCompleteProperties.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LendingCompleteProperties} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LendingCompleteProperties}
 */
proto.LendingCompleteProperties.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new IssuanceData_pb.IssuanceProperties;
      reader.readMessage(value,IssuanceData_pb.IssuanceProperties.deserializeBinaryFromReader);
      msg.setIssuanceproperties(value);
      break;
    case 2:
      var value = new proto.LendingProperties;
      reader.readMessage(value,proto.LendingProperties.deserializeBinaryFromReader);
      msg.setLendingproperties(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LendingCompleteProperties.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.LendingCompleteProperties.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LendingCompleteProperties} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LendingCompleteProperties.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIssuanceproperties();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      IssuanceData_pb.IssuanceProperties.serializeBinaryToWriter
    );
  }
  f = message.getLendingproperties();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.LendingProperties.serializeBinaryToWriter
    );
  }
};


/**
 * optional IssuanceProperties issuanceProperties = 1;
 * @return {?proto.IssuanceProperties}
 */
proto.LendingCompleteProperties.prototype.getIssuanceproperties = function() {
  return /** @type{?proto.IssuanceProperties} */ (
    jspb.Message.getWrapperField(this, IssuanceData_pb.IssuanceProperties, 1));
};


/** @param {?proto.IssuanceProperties|undefined} value */
proto.LendingCompleteProperties.prototype.setIssuanceproperties = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.LendingCompleteProperties.prototype.clearIssuanceproperties = function() {
  this.setIssuanceproperties(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LendingCompleteProperties.prototype.hasIssuanceproperties = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional LendingProperties lendingProperties = 2;
 * @return {?proto.LendingProperties}
 */
proto.LendingCompleteProperties.prototype.getLendingproperties = function() {
  return /** @type{?proto.LendingProperties} */ (
    jspb.Message.getWrapperField(this, proto.LendingProperties, 2));
};


/** @param {?proto.LendingProperties|undefined} value */
proto.LendingCompleteProperties.prototype.setLendingproperties = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.LendingCompleteProperties.prototype.clearLendingproperties = function() {
  this.setLendingproperties(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LendingCompleteProperties.prototype.hasLendingproperties = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto);
